### PR TITLE
Add default value for 'shots' in config.json

### PR DESCRIPTION
**Pull request by anushreejha**
This PR adds a default value of 100 for the shots field in config.json, making it an optional entry. If shots is not specified in the configuration, it will default to 100.

### CODE REVIEW

**Comment by mghibaudi** [comment]
hi @anushreejha - looking into why the runner fails on coverage - your change looks good and CI should pass

**Comment by mghibaudi** [comment]
@anushreejha - fixed the action execution from a fork, would you mind updating your fork with the latest from this main? Thanks for your contribution and for your patience!

**Comment by anushreejha** [comment]
@mghibaudi Thank you for the fix and the guidance! I’ve updated my fork with the latest changes from the main repository and pushed the updates to my branch. Please let me know if you need anything else from my side.

**Comment by mghibaudi** [comment]
Manual run passes fine. The issue with coverage comes from token/secrets not visible via fork. Merging.

**Pull request merged**
